spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 544ed67fb1388bed1d75
            clientSecret: e934104770bceae1aa57ad85d42d5c647415a2a2
opennode:
   api:
      apiEndpoint: https://dev-api.opennode.com
      appEndpoint: https://dev.opennode.com
sendinblue:
   api:
      adminEmail: mike@thisisnumberone.com
      emailTemplate1Url: https://staging.thisisnumberone.com/Email.html
      emailTemplate1: EmailTemplate1.html
      key: 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
mandrill:
   api:
      key: 9Pk36qtppNlJeeWdqClyeQ
squareup:
   api:
      applicationName: rpay-prom
      redirectUrl: https://tapi.risidio.com/mesh/oauth-redirect
radicle:
   security:
      enable-csrf: false
   gaia:
      huburl: https://core.blockstack.org/v1/users/
   search:
      indexurl: http://docker.for.mac.localhost:8048/index/indexMetaData/
   mongo:
      mongoIp: mongodb://mongodb
      mongoPort: 27017
      mongoDbName: mesh
   stx-mining:
      mining-path: http://monitor.stxmining.xyz/mining_info
   binance:
      rate-path: https://api.binance.com/api/v3/ticker/24hr
      fiat-list: GBP,USD,EUR,AUD,JPY,HKD
   ticker:
      rate-path: https://blockchain.info/ticker
   btcfee:
      fee-rate: https://bitcoinfees.earn.com/api/v1/fees/recommended
      fee-list: https://bitcoinfees.earn.com/api/v1/fees/list
   stax:
      base-path: http://docker.for.mac.localhost:20443
      sidecar-path: http://docker.for.mac.localhost:3999
      admin-contract-address: ST1ESYCGJB5Z5NBHS39XPC70PGC14WAQK5XXNQYDW
      admin-contract-name: appmap-v1
cloudinary:
   cloudName: mijo-enterprises
   baseDeliveryUrl: http://res.cloudinary.com/mijo-enterprises
   secureDeliveryUrl: https://res.cloudinary.com/mijo-enterprises
   apiBaseUrl: https://api.cloudinary.com/v1_1/mijo-enterprises

---

spring:
   profiles: test
application:
   mongoIp: mongodb://localhost
radicle:
   stax:
      base-path: http://139.162.204.44:20443
      sidecar-path: http://139.162.204.44:3999

---

spring:
    profiles: linux-dev
application:
   mongoIp: mongodb://localhost
radicle:
   stax:
      base-path: http://172.17.0.1:20443
      sidecar-path: http://172.17.0.1:3999

---

spring:
    profiles: docker-dev
application:
   mongoIp: mongodb://localhost
radicle:
   stax:
      base-path: http://139.162.204.44:20443
      sidecar-path: http://139.162.204.44:3999

---

spring:
    profiles: staging
application:
   mongoIp: mongodb://mongodb
   mongoPort: 27017
squareup:
   api:
      applicationName: rpay-prom
      redirectUrl: https://tapi.risidio.com/mesh/oauth-redirect
radicle:
   search:
      indexurl: http://172.17.0.1:8046/index/indexMetaData/
   stax:
      base-path: http://139.162.204.44:20443
      sidecar-path: http://139.162.204.44:3999
      admin-contract-address: ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT
      admin-contract-name: appmap-v3

---

spring:
    profiles: production
application:
   mongoIp: mongodb://mongodb
   mongoPort: 27017
sendinblue:
   api:
      emailTemplate1Url: https://thisisnumberone.com/Email.html
squareup:
   api:
      applicationName: rpay-prom
      redirectUrl: https://api.risidio.com/mesh/oauth-redirect
opennode:
   api:
      apiEndpoint: https://api.opennode.com
      appEndpoint: https://app.opennode.com
radicle:
   search:
      indexurl: http://172.17.0.1:8046/index/indexMetaData/
   stax:
      base-path: http://178.79.138.62:20443
      sidecar-path: http://178.79.138.62:3999
      admin-contract-address: SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ
      admin-contract-name: appmap-v1
   